export const ADD_TODO = 'ADD_TODO'
export const GET_TODOS = 'GET_TODOS'
export const ADD_LIST = 'ADD_LIST'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const LOAD_TODOS_LS = 'LOAD_TODOS_LS'
